"""
Disctionary of Enums used by the Ordertime API
"""


RecordTypeEnum = {
    "Adjustment": 1,
    "Receiver": 2,
    "Work Order": 3,
    "Ship Doc": 4,
    "Transfer": 5,
    "Purchase Order": 6,
    "Sales Order": 7,
    "Customer Return": 10,
    "Quote": 13,
    "Item": 100,
    "Part Item": 101,
    "Non Part Item": 103,
    "Service Item": 105,
    "Assembly Item": 107,
    "Other Charge Item": 108,
    "Customer": 120,
    "Vendor": 130,
    "Location": 150,
    "Bin": 151,
    "UOM": 160,
    "UOM Set": 162,
    "Currency": 170,
    "Item Group": 180,
    "Term": 190,
    "Payment Method": 200,
    "Manufacturer": 220,
    "Related Items": 230,
    "Ship Method": 250,
    "FOB": 260,
    "Discount": 270,
    "Price Level": 280,
    "Customer Type": 300,
    "Sales Tax Code": 320,
    "Customer Alias": 330,
    "Account": 350,
    "Sales Rep": 370,
    "Class": 380,
    "Tax Item": 390,
    "Lead": 500,
    "Lead Status": 510,
    "Warranty Type": 610,
    "Doc Status": 630,
    "Customer Address": 121,
    "Contact": 122,
    "Sales Order Line Item": 1000,
    "Purchase Order Line Item": 1040,
    "Item Image": 1060,
    "Ship Doc Line Item": 1070,
    "Receiver Line Item": 1080,
    "Adjustment Line Item": 1090,
    "Transfer Line Item": 1095,
    "Lot or Serial Number": 1100,
    "Inventory": 1110,
    "Inventory Status by Item": 1111,
    "Inventory Status by Location": 1112,
    "Item Transaction": 2600,
    "On Order Detail": 2610,
    "Required Detail": 2620,
    "Item Bar code": 3080,
    "Volume Price Level Detail": 284,
}

# EqualTo is the default filter
FilterOpEnum = {
    "EqualTo": 1,
    "GreaterThan": 2,
    "LessThan": 3,
    "GreaterThanOrEqualTo": 4,
    "LessThanOrEqualTo": 5,
    "NotEqualTo": 6,
    "In": 8,
    "NotIn": 9,
    "IsNull": 10,
    "NotIsNull": 11,
    "Like": 12,
    "NotLike": 13,
}

SortDirEnum = {"Asc": 1, "Desc": 2}

DateMacroEnum = {
    "all": 0,
    "today": 1,
    "week": 2,
    "weektodate": 3,
    "month": 4,
    "monthdodate": 5,
    "quarter": 6,
    "quartertodate": 7,
    "year": 8,
    "yeartodate": 9,
    "yesterday": 10,
    "lastweek": 11,
    "lastweektodate": 12,
    "lastmonth": 13,
    "lastmonthtodate": 14,
    "lastquarter": 15,
    "lastquartertodate": 16,
    "lastyear": 17,
    "lastyeartodate": 18,
    "nextweek": 19,
    "next4weeks": 20,
    "nextmonth": 21,
    "nextquarter": 22,
    "nextyear": 23,
    "trailing12months": 24,
    "custom": 25,
}
